package:
  name: gensim
  version: 4.1.2
source:
  url: https://files.pythonhosted.org/packages/4b/6d/22a9a2b934344fbf25ab2613543eeeb724ffd3ba7376e8fed88aabe885c8/gensim-4.1.2.tar.gz
  sha256: 1932c257de4eccbb64cc40d46e8577a25f5f47b94b96019a969fb36150f11d15
test:
  imports:
  - gensim
requirements:
  run:
    - dataclasses  # [py<37]
    - numpy
    - scipy
    - six
    - smart_open
about:
  home: http://radimrehurek.com/gensim
  PyPi: https://pypi.org/project/gensim
  summary: Python framework for fast Vector Space Modelling
  license: LGPL-2.1-only
