package:
  name: sparqlwrapper
  version: 1.8.5
source:
  url: https://files.pythonhosted.org/packages/bb/cb/84fafd4f628fcf83795ff7f377fa8211a12655adf8bc288698bdb2415cb3/SPARQLWrapper-1.8.5.tar.gz
  sha256: d6a66b5b8cda141660e07aeb00472db077a98d22cb588c973209c7336850fb3c
test:
  imports:
  - sparqlwrapper
requirements:
  run:
  - keepalive
about:
  home: http://rdflib.github.io/sparqlwrapper
  PyPi: https://pypi.org/project/sparqlwrapper
  summary: SPARQL Endpoint interface to Python
  license: W3C SOFTWARE NOTICE AND LICENSE
