package:
  name: dataclasses
  version: '0.8'
source:
  url: https://files.pythonhosted.org/packages/1f/12/7919c5d8b9c497f9180db15ea8ead6499812ea8264a6ae18766d93c59fe5/dataclasses-0.8.tar.gz
  sha256: 8479067f342acf957dc82ec415d355ab5edb7e7646b90dc6e2fd1d96ad084c97
test:
  imports:
  - dataclasses
about:
  home: https://github.com/ericvsmith/dataclasses
  PyPi: https://pypi.org/project/dataclasses
  summary: A backport of the dataclasses module for Python 3.6
  license: Apache
