package:
  name: kglab
  version: 0.4.2
source:
  url: https://www.dropbox.com/s/d6rz5cfgmkmx46d/kglab-0.4.2.1.tar.gz?raw=1
  sha256: fff3438ba4e543c0a56d198b53ae69d8d5e6cbff51b964199778633947c151c6
  # url: https://files.pythonhosted.org/packages/20/e2/4064fc18876b02a0323186695a049794edd51e0d5b7432f29aa1272c5ebe/kglab-0.4.2.tar.gz
  # sha256: ef71f36c93f5519c206ea2d9637738cf1432a9f80079f890d5cf232638f7c2a6
requirements:
  run:
    - chocolate #>=0.0.2
    - csvwlib #>=0.3.2
    - decorator #wanted>=4.4.2 have 5.0.9
    - fsspec #>=0.8.5
    - gcsfs #wanted >=0.7.1 have 2021.11.1
    - gensim #>=3.8.3
    - icecream #>=2.0
    - matplotlib #-base #>=3.3.4
    - networkx #want >=2.6 , have  2.5.1
    - numpy #>=1.19.4
    - owlrl #>=6.0.2
    - pandas #>=1.1.5
    #### - pslpython >=2.2.2 #use wheel https://pypi.org/project/pslpython/#files
    # - pyarrow #>=2.0.0
    - pygments #want >=2.7.4 have 2.9.0
    - pylev #>=1.3
    - pynvml #>=8.0.4
    - pyshacl # >=0.17.3
    - python-dateutil
    #- pyvis # want >=0.1.7.0 have 0.1.9 #error: decorator 5.0.9 is installed but decorator<5,>=4.3 is required by {'networkx'} #error: decorator 5.0.9 is installed but decorator<5,>=4.3 is required by {'networkx'} # also Jinja2 assert self.name == pkgdir.stem assertion error
    - rdflib #not sure why version number didn't work
    - requests #have 2.26.0 wanted # =2.25.1
    - scikit-learn
    - statsmodels #have 0.8, called for 1.2
    # # - torch >=1.8 # use wheel
    - tqdm #>=4.56
    - urlpath #>=1.1.7
test:
  imports:
  - kglab
about:
  home: https://derwen.ai/docs/kgl/
  PyPi: https://pypi.org/project/kglab
  summary: A simple abstraction layer in Python for building knowledge graphs
  license: MIT


#     - chocolate >=0.0.2
#     - csvwlib >=0.3.2
#     - decorator >=4.4.2
#     - fsspec >=0.8.5
#     - gcsfs >=0.7.1
#     - gensim >=3.8.3
#     - icecream >=2.0
#     - matplotlib-base >=3.3.4
#     - networkx >=2.6
#     - numpy >=1.19.4
#     - owlrl >=6.0.2
#     - pandas >=1.1.5
#     # - pslpython >=2.2.2 https://pypi.org/project/pslpython/#files
#     - pyarrow >=2.0.0
#     - pygments >=2.7.4
#     - pylev >=1.3
#     - pynvml >=8.0.4
#     - pyshacl >=0.17.3
#     - python >=3.6
#     - python-dateutil >=2.8
#     - pyvis >=0.1.7.0
#     - rdflib
#     - requests >=2.25.1
#     - scikit-learn >=0.20.2
#     - statsmodels >=0.12
#     # - torch >=1.8
#     - tqdm >=4.56
#     - urlpath >=1.1.7
# test: