package:
  name: tqdm
  version: 4.62.3
source:
  url: https://files.pythonhosted.org/packages/e3/c1/b3e42d5b659ca598508e2a9ef315d5eef0a970f874ef9d3b38d4578765bd/tqdm-4.62.3.tar.gz
  sha256: d359de7217506c9851b7869f3708d8ee53ed70a1b8edbba4dbcb47442592920d
requirements:
  run:
  - colorama
test:
  imports:
  - tqdm
about:
  home: https://tqdm.github.io
  PyPi: https://pypi.org/project/tqdm
  summary: Fast, Extensible Progress Meter
  license: MPLv2.0, MIT Licences
