package:
  name: colorama
  version: 0.4.4
source:
  url: https://files.pythonhosted.org/packages/1f/bb/5d3246097ab77fa083a61bd8d3d527b7ae063c7d8e8671b1cf8c4ec10cbe/colorama-0.4.4.tar.gz
  sha256: 5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b
test:
  imports:
  - colorama
about:
  home: https://github.com/tartley/colorama
  PyPi: https://pypi.org/project/colorama
  summary: Cross-platform colored terminal text.
  license: BSD
